name: cloakly_mobile
description: Cloakly 官方託管手機版。
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cloakly_core:
    path: ../../packages/cloakly_core
  supabase_flutter: ^2.17.2
  purchases_flutter: ^10.13.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
